services:
  node-backend:
    user: "1000:1000"
    build: ./BackEnd
    ports:
      - "3000:3000"
    volumes:
      - ./BackEnd:/app
      - /home/ubuntu/weather_cloth_3/data:/weather_cloth_3/data:rw  # ← 이렇게 변경
    env_file:
      - ./BackEnd/.env
    environment:
      - CONTAINER_DATA_DIR=/weather_cloth_3/data  # ← 이렇게 변경
      - DATA_DIR=/weather_cloth_3/data            # ← 이렇게 변경
    depends_on:
      - redis

  redis:
    image: redis:8.0.3
    ports:
      - "6379:6379"